import type { Position } from "./detectType";

export type Strategy = {
  id: number;
  slug: string;
  name: string;
  aliases: string[];
  level: "Novice" | "Intermediate" | "Advanced" | "Expert";
  sentiment: ("bullish" | "bearish" | "neutral" | "directional" | "income")[];
  category: "Basic" | "Income" | "Other" | "Credit Spreads" | "Debit Spreads" | "Neutral" | "Directional" | "Calendar Spreads" | "Naked" | "Ladders" | "Ratio Spreads" | "Synthetic" | "Arbitrage";
  description: string;
  template: Position[];
};

export const strategies = {
  empty: {
    id: 107,
    slug: "empty",
    name: "Empty",
    aliases: [],
    level: "Novice",
    sentiment: [],
    category: "Other",
    description: "",
    template: [],
  },
  longCall: {
    id: 1,
    slug: "long-call",
    name: "Long Call",
    aliases: [],
    level: "Novice",
    sentiment: ["bullish"],
    category: "Basic",
    description:
      "A simple bullish strategy for beginners that can yield big rewards. A call gives the buyer the right, but not the obligation, to buy the underlying stock at strike price A. However, you can simply buy and sell a call before it expires to profit off the price change. The value of the option will decay as time passes, and is sensitive to changes in volatility. Your maximum loss is capped at the price you pay for the option.",
    template: [
      {
        type: "call",
        position: 1,
        strike: 0,
        dte: 30,
      },
    ],
  },
  longPut: {
    id: 2,
    slug: "long-put",
    name: "Long Put",
    aliases: [],
    level: "Novice",
    sentiment: ["bearish"],
    category: "Basic",
    description:
      "A simple bearish strategy for beginners that can yield big rewards. A put gives the buyer the right, but not the obligation, to sell the underlying stock at strike price A. However, you can simply buy and sell a put before it expires to profit off the price change. The value of the option will decay as time passes, and is sensitive to changes in volatility. Your maximum loss is capped at the price you pay for the option.",
    template: [
      {
        type: "put",
        position: 1,
        strike: 0,
        dte: 30,
      },
    ],
  },
  shortCall: {
    id: 3,
    slug: "short-call",
    name: "Short Call",
    aliases: ["Naked Call"],
    level: "Advanced",
    sentiment: ["bearish"],
    category: "Naked",
    description: "A simple but risky strategy which results in an initial credit. By selling a call, you are liable to sell 100 shares of the underlying stock at strike price A if assigned. Because of this, you should have the cash or stock to cover such a situation. If it expires below strike A, you simply keep the full credit.",
    template: [
      {
        type: "call",
        position: -1,
        strike: 0,
        dte: 30,
      },
    ],
  },
  shortPut: {
    id: 4,
    slug: "short-put",
    name: "Short Put",
    aliases: ["Naked Put"],
    level: "Advanced",
    sentiment: ["bullish"],
    category: "Naked",
    description: "A simple but risky strategy which results in an initial credit. By selling a put, you are liable to buy 100 shares of the underlying stock at strike price A if assigned. Because of this, you should be okay with buying the stock at such a price. If it expires above strike A, you simply keep the full credit.",
    template: [
      {
        type: "put",
        position: -1,
        strike: 0,
        dte: 30,
      },
    ],
  },
  coveredCall: {
    id: 5,
    slug: "covered-call",
    name: "Covered Call",
    aliases: [],
    level: "Novice",
    sentiment: ["income"],
    category: "Income",
    description:
      "A simple income strategy for neutral to slightly-bullish situations when you are willing to sell your stock at strike price A. If you own 100 shares of the underlying stock, you can use a covered call to generate income or sell your position at a favorable price. If the stock reaches strike price A, the call will be assigned and your stock will be sold (but at a profit!). If it stays below the strike, you will collect the full premium to make a bit of income. The downside is that you could part ways with your stock at a price much lower than the current stock price, leaving potential profit on the table.",
    template: [
      {
        type: "call",
        position: -1,
        strike: 5,
        dte: 30,
      },
      {
        type: "stock",
        position: 1,
      },
    ],
  },
  protectivePut: {
    id: 6,
    slug: "protective-put",
    name: "Protective Put",
    aliases: [],
    level: "Novice",
    sentiment: [],
    category: "Other",
    description:
      'A simple strategy to limit your losses on when you are bullish but nervous on a stock. If you own 100 shares of an underlying stock and the price falls below strike A, you can exercise your put to sell your position at strike price A. This is similar to a stop loss (which is free), but it guarantees the selling price, whereas a limit stop-loss may not be executed and a market stop-loss may be at an unfavorable price. The disadvantage is that if the stock goes up, you will have reduced your potential profit by the cost of the put. This "insurance" may be worth it however.',
    template: [
      {
        type: "put",
        position: 1,
        strike: -5,
        dte: 30,
      },
      {
        type: "stock",
        position: 1,
      },
    ],
  },
  bullCallSpread: {
    id: 7,
    slug: "bull-call-spread",
    name: "Bull Call Spread",
    aliases: ["Call Debit Spread"],
    level: "Intermediate",
    sentiment: ["bullish"],
    category: "Debit Spreads",
    description: "A bullish vertical spread strategy which has limited risk and reward. It combines a long and short call which caps the upside, but also the downside. The goal is for the stock to be above strike B at expiration. This strategy is almost neutral to changes in volatility. Time-decay is helpful while it is profitable, but harmful when it is losing.",
    template: [
      {
        type: "call",
        position: 1,
        strike: 0,
        dte: 30,
      },
      {
        type: "call",
        position: -1,
        strike: 5,
        dte: 30,
      },
    ],
  },
  bearCallSpread: {
    id: 8,
    slug: "bear-call-spread",
    name: "Bear Call Spread",
    aliases: ["Call Credit Spread"],
    level: "Intermediate",
    sentiment: ["bearish"],
    category: "Credit Spreads",
    description: "A bearish vertical spread strategy which has limited risk and reward. It combines a short and a long call which caps the upside, but also the downside. The goal is for the stock to be below strike A, which allows both calls to expire worthless. This strategy is almost neutral to changes in volatility. Time-decay is helpful while it is profitable, but harmful when it is losing.",
    template: [
      {
        type: "call",
        position: -1,
        strike: -5,
        dte: 30,
      },
      {
        type: "call",
        position: 1,
        strike: 0,
        dte: 30,
      },
    ],
  },
  bullPutSpread: {
    id: 9,
    slug: "bull-put-spread",
    name: "Bull Put Spread",
    aliases: ["Put Credit Spread"],
    level: "Intermediate",
    sentiment: ["bullish"],
    category: "Credit Spreads",
    description: "A bullish vertical spread strategy which has limited risk and reward. It combines a long and short put which caps the upside, but also the downside. The goal is for the stock to be above strike B, which allows both puts to expire worthless. This strategy is almost neutral to changes in volatility. Time-decay is helpful while it is profitable, but harmful when it is losing.",
    template: [
      {
        type: "put",
        position: 1,
        strike: -5,
        dte: 30,
      },
      {
        type: "put",
        position: -1,
        strike: 0,
        dte: 30,
      },
    ],
  },
  bearPutSpread: {
    id: 10,
    slug: "bear-put-spread",
    name: "Bear Put Spread",
    aliases: ["Put Debit Spread"],
    level: "Intermediate",
    sentiment: ["bearish"],
    category: "Debit Spreads",
    description: "A bearish vertical spread strategy which has limited risk and reward. It combines a short and a long put which caps the upside, but also the downside. The goal is for the stock to be below strike A at expiration. This strategy is almost neutral to changes in volatility. Time-decay is helpful while it is profitable, but harmful when it is losing.",
    template: [
      {
        type: "put",
        position: -1,
        strike: 0,
        dte: 30,
      },
      {
        type: "put",
        position: 1,
        strike: 5,
        dte: 30,
      },
    ],
  },
  calendarCallSpread: {
    id: 11,
    slug: "calendar-call-spread",
    name: "Calendar Call Spread",
    aliases: ["Horizontal Call Spread"],
    level: "Intermediate",
    sentiment: ["neutral"],
    category: "Calendar Spreads",
    description: "A neutral to mildly bearish/bullish strategy using two calls of the same strike, but different expiration dates. If the stock is near strike A when the earlier call expires, you will be able to close it for a profit. Use an at-the-money strike to make this strategy neutral, or a slightly out-of-the-money or in-the-money strike to give a bullish or bearish bias.",
    template: [
      {
        type: "call",
        position: -1,
        strike: 0,
        dte: 30,
      },
      {
        type: "call",
        position: 1,
        strike: 0,
        dte: 60,
      },
    ],
  },
  diagonalCallSpread: {
    id: 12,
    slug: "diagonal-call-spread",
    name: "Diagonal Call Spread",
    aliases: ["Poor Man's Covered Call"],
    level: "Intermediate",
    sentiment: ["bullish"],
    category: "Calendar Spreads",
    description: "A variation of the calendar spread where the long (later expiration) call is further in the money, which changes the shape of the risk profile.",
    template: [
      {
        type: "call",
        position: -1,
        strike: 5,
        dte: 30,
      },
      {
        type: "call",
        position: 1,
        strike: -5,
        dte: 60,
      },
    ],
  },
  collar: {
    id: 13,
    slug: "collar",
    name: "Collar",
    aliases: ["Risk-reversal"],
    level: "Intermediate",
    sentiment: ["bullish"],
    category: "Other",
    description:
      "A strategy for when you are somewhat bullish but nervous on a stock, and own 100 of the underlying shares. It is like a covered call and protective put combined because it protects you from the stock falling past strike A, but also limits your upside by selling the stock if it hits strike B. You can also think of it like a protective put, but the credit from the short call pays  for the stop-loss insurance, with the downside of the profit being capped.",
    template: [
      {
        type: "put",
        position: 1,
        strike: -5,
        dte: 30,
      },
      {
        type: "call",
        position: -1,
        strike: 5,
        dte: 30,
      },
      {
        type: "stock",
        position: 1,
      },
    ],
  },
  straddle: {
    id: 14,
    slug: "straddle",
    name: "Straddle",
    aliases: [],
    level: "Intermediate",
    sentiment: ["directional"],
    category: "Directional",
    description:
      "A straddle is an easy to understand volatility strategy that allows you to profit from moves in either direction. Since it involves buying both a call and a put, it is an expensive strategy and needs a big move to cover its cost. Time is harmful to this strategy since it is made up of long options, but volatility is your friend. You may consider buying a straddle before earnings to profit off any big move after earnings (but keep IV crush in mind!), or to take advantage of the rising IV before earnings.",
    template: [
      {
        type: "put",
        position: 1,
        strike: 0,
        dte: 30,
      },
      {
        type: "call",
        position: 1,
        strike: 0,
        dte: 30,
      },
    ],
  },
  strangle: {
    id: 15,
    slug: "strangle",
    name: "Strangle",
    aliases: [],
    level: "Intermediate",
    sentiment: ["directional"],
    category: "Directional",
    description: "A strangle is similar to a straddle, except that the put and call are at different strikes. These out-of-the-money options make a strangle cheaper than a straddle, but require a bigger move to make a profit.",
    template: [
      {
        type: "put",
        position: 1,
        strike: -5,
        dte: 30,
      },
      {
        type: "call",
        position: 1,
        strike: 5,
        dte: 30,
      },
    ],
  },
  longCallButterfly: {
    id: 16,
    slug: "long-call-butterfly",
    name: "Long Call Butterfly",
    aliases: [],
    level: "Intermediate",
    sentiment: ["neutral"],
    category: "Neutral",
    description: "A call butterfly spread is the combination of a bull call spread and a bear call spread. This creates a neutral strategy that is cheap and has a good risk/reward ratio. Decreasing volatility will increase the profitable area, while increasing volatility will narrow the profitable range. Time is helpful when the position is profitable, and harmful when it isn't.",
    template: [
      {
        type: "call",
        position: 1,
        strike: -5,
        dte: 30,
      },
      {
        type: "call",
        position: -2,
        strike: 0,
        dte: 30,
      },
      {
        type: "call",
        position: 1,
        strike: 5,
        dte: 30,
      },
    ],
  },
  longPutButterfly: {
    id: 17,
    slug: "long-put-butterfly",
    name: "Long Put Butterfly",
    aliases: [],
    level: "Intermediate",
    sentiment: ["neutral"],
    category: "Neutral",
    description: "A put butterfly spread is the combination of a bull put spread and a bear put spread. This creates a neutral strategy that is cheap and has a good risk/reward ratio. Decreasing volatility will increase the profitable area, while increasing volatility will narrow the profitable range. Time is helpful when the position is profitable, and harmful when it isn't.",
    template: [
      {
        type: "put",
        position: 1,
        strike: -5,
        dte: 30,
      },
      {
        type: "put",
        position: -2,
        strike: 0,
        dte: 30,
      },
      {
        type: "put",
        position: 1,
        strike: 5,
        dte: 30,
      },
    ],
  },
  ironButterfly: {
    id: 18,
    slug: "iron-butterfly",
    name: "Iron Butterfly",
    aliases: ["Short Iron Butterfly"],
    level: "Intermediate",
    sentiment: ["neutral"],
    category: "Neutral",
    description:
      "An iron butterfly has similar characteristics to a put or call butterfly, but is established as a net credit. It is made of a combination of a bull put spread and a bear call spread. Decreasing volatility will increase the profitable area and chance of profit, while increasing volatility will narrow the profitable range. Time is helpful when the position is profitable, and harmful when it isn't.",
    template: [
      {
        type: "put",
        position: 1,
        strike: -5,
        dte: 30,
      },
      {
        type: "put",
        position: -1,
        strike: 0,
        dte: 30,
      },
      {
        type: "call",
        position: -1,
        strike: 0,
        dte: 30,
      },
      {
        type: "call",
        position: 1,
        strike: 5,
        dte: 30,
      },
    ],
  },
  ironCondor: {
    id: 19,
    slug: "iron-condor",
    name: "Iron Condor",
    aliases: ["Short Iron Condor"],
    level: "Intermediate",
    sentiment: ["neutral"],
    category: "Neutral",
    description:
      "An iron condor is a neutral strategy that is profitable if the stock remains within the inner strikes B and C. It is established for a net credit and has a wider profitable range than an iron butterfly, but the potential profit is lower. Decreasing volatility will increase the profitable area and chance of profit, while increasing volatility will narrow the profitable range. Time is helpful when the position is profitable, and harmful when it isn't.",
    template: [
      {
        type: "put",
        position: 1,
        strike: -10,
        dte: 30,
      },
      {
        type: "put",
        position: -1,
        strike: -5,
        dte: 30,
      },
      {
        type: "call",
        position: -1,
        strike: 5,
        dte: 30,
      },
      {
        type: "call",
        position: 1,
        strike: 10,
        dte: 30,
      },
    ],
  },
  shortCallButterfly: {
    id: 20,
    slug: "short-call-butterfly",
    name: "Short Call Butterfly",
    aliases: [],
    level: "Intermediate",
    sentiment: ["directional"],
    category: "Directional",
    description: "A short call butterfly is a volatility strategy that can be profitable if there is a big move in either direction. It is the opposite of a long call butterfly. Increasing volatility or a big move is required for this strategy to become profitable. Time is harmful when the position is unprofitable, but helpful once it becomes profitable.",
    template: [
      {
        type: "call",
        position: -1,
        strike: -5,
        dte: 30,
      },
      {
        type: "call",
        position: 2,
        strike: 0,
        dte: 30,
      },
      {
        type: "call",
        position: -1,
        strike: 5,
        dte: 30,
      },
    ],
  },
  shortPutButterfly: {
    id: 21,
    slug: "short-put-butterfly",
    name: "Short Put Butterfly",
    aliases: [],
    level: "Intermediate",
    sentiment: ["directional"],
    category: "Directional",
    description: "A short put butterfly is a volatility strategy that can be profitable if there is a big move in either direction. It is the opposite of a long put butterfly. Increasing volatility or a big move is required for this strategy to become profitable. Time is harmful when the position is unprofitable, but helpful once it becomes profitable.",
    template: [
      {
        type: "put",
        position: -1,
        strike: -5,
        dte: 30,
      },
      {
        type: "put",
        position: 2,
        strike: 0,
        dte: 30,
      },
      {
        type: "put",
        position: -1,
        strike: 5,
        dte: 30,
      },
    ],
  },
  bullCallLadder: {
    id: 22,
    slug: "bull-call-ladder",
    name: "Bull Call Ladder",
    aliases: ["Long Call Ladder"],
    level: "Advanced",
    sentiment: ["neutral"],
    category: "Ladders",
    description:
      "A bull call ladder is an extension to the bull call spread, as it now includes another short call. This increases the max profit potential, but introduces infinite risk. The name suggests that it is a bullish strategy, but it is actually neutral to slightly bullish since it has uncapped loss if a large upwards move is made. Time is harmful when the stock is near the lower strike, but becomes most helpful near the upper strikes. Decreasing volatility is helpful and increases the chance of staying in the profitable range.",
    template: [
      {
        type: "call",
        position: 1,
        strike: -5,
        dte: 30,
      },
      {
        type: "call",
        position: -1,
        strike: 0,
        dte: 30,
      },
      {
        type: "call",
        position: -1,
        strike: 5,
        dte: 30,
      },
    ],
  },
  bearCallLadder: {
    id: 23,
    slug: "bear-call-ladder",
    name: "Bear Call Ladder",
    aliases: ["Short Call Ladder"],
    level: "Advanced",
    sentiment: ["directional"],
    category: "Ladders",
    description:
      "A bear call ladder is an extension to the bear call spread, as it now includes another long call. The name suggests it is a bearish strategy, but it is actually bearish or very bullish, since it has a capped gain on the downside and an infinite gain on the upside. This strategy requires significant volatility to be profitable. Time is harmful when the position is unprofitable, but helpful once it becomes profitable.",
    template: [
      {
        type: "call",
        position: -1,
        strike: -5,
        dte: 30,
      },
      {
        type: "call",
        position: 1,
        strike: 0,
        dte: 30,
      },
      {
        type: "call",
        position: 1,
        strike: 5,
        dte: 30,
      },
    ],
  },
  bullPutLadder: {
    id: 24,
    slug: "bull-put-ladder",
    name: "Bull Put Ladder",
    aliases: ["Short Put Ladder"],
    level: "Advanced",
    sentiment: ["directional"],
    category: "Ladders",
    description:
      "A bull put ladder is an extension to the bull put spread, as it now includes another long put. The name suggests it is a bullish strategy, but it is actually very bearish or bullish, since it has a nearly infinite gain on the downside, and a capped gain on the upside. This strategy requires significant volatility to be profitable. Time is harmful when the position is unprofitable, but helpful once it becomes profitable.",
    template: [
      {
        type: "put",
        position: 1,
        strike: -5,
        dte: 30,
      },
      {
        type: "put",
        position: 1,
        strike: 0,
        dte: 30,
      },
      {
        type: "put",
        position: -1,
        strike: 5,
        dte: 30,
      },
    ],
  },
  bearPutLadder: {
    id: 25,
    slug: "bear-put-ladder",
    name: "Bear Put Ladder",
    aliases: ["Long Put Ladder"],
    level: "Advanced",
    sentiment: ["neutral"],
    category: "Ladders",
    description:
      "A bear put ladder is an extension to the bear put spread, as it now includes another short put. The name suggests it is a bearish strategy, but it is actually neutral to slightly bearish since it has a nearly uncapped loss on the downside.Time is helpful when the position is profitable, and harmful when it isn't. Decreasing volatility is helpful and increases the chance of staying in the profitable range.",
    template: [
      {
        type: "put",
        position: -1,
        strike: -5,
        dte: 30,
      },
      {
        type: "put",
        position: -1,
        strike: 0,
        dte: 30,
      },
      {
        type: "put",
        position: 1,
        strike: 5,
        dte: 30,
      },
    ],
  },
  calendarPutSpread: {
    id: 26,
    slug: "calendar-put-spread",
    name: "Calendar Put Spread",
    aliases: ["Horizontal Put Spread"],
    level: "Intermediate",
    sentiment: ["neutral"],
    category: "Calendar Spreads",
    description: "A neutral to mildly bearish/bullish strategy using two puts of the same strike, but different expiration dates. If the stock is near strike A when the earlier call expires, you will be able to close it for a profit. Use an at-the-money strike to make this strategy neutral, or a slightly out-of-the-money or in-the-money strike to give a bullish or bearish bias.",
    template: [
      {
        type: "put",
        position: -1,
        strike: 0,
        dte: 30,
      },
      {
        type: "put",
        position: 1,
        strike: 0,
        dte: 60,
      },
    ],
  },
  diagonalPutSpread: {
    id: 27,
    slug: "diagonal-put-spread",
    name: "Diagonal Put Spread",
    aliases: [],
    level: "Intermediate",
    sentiment: ["bearish"],
    category: "Calendar Spreads",
    description: "A variation of the calendar spread where the long (later expiration) put is further in the money, which changes the shape of the risk profile.",
    template: [
      {
        type: "put",
        position: -1,
        strike: -5,
        dte: 30,
      },
      {
        type: "put",
        position: 1,
        strike: 5,
        dte: 60,
      },
    ],
  },
  callRatioBackspread: {
    id: 28,
    slug: "call-ratio-backspread",
    name: "Call Ratio Backspread",
    aliases: [],
    level: "Advanced",
    sentiment: ["bullish"],
    category: "Ratio Spreads",
    description: "An extremely bullish  strategy that gives great profits when the stock makes a big upwards move, and a loss if it only moves a bit. If established for a net credit and the stock goes down, you can actually still make a small amount. Time is generally harmful to this strategy, and increasing volatility is helpful.",
    template: [
      {
        type: "call",
        position: -1,
        strike: 0,
        dte: 30,
      },
      {
        type: "call",
        position: 2,
        strike: 5,
        dte: 30,
      },
    ],
  },
  putRatioBackspread: {
    id: 29,
    slug: "put-ratio-backspread",
    name: "Put Ratio Backspread",
    aliases: [],
    level: "Advanced",
    sentiment: ["bearish"],
    category: "Ratio Spreads",
    description: "The opposite of a call ratio backspread. This is an extremely bearish strategy that gives great profits when the stock makes a big downwords move, and a loss if it only moves a bit. If established for a net credit and the stock goes up, you can actually still make a small amount. Time is generally harmful to this strategy, and increasing volatility is helpful.",
    template: [
      {
        type: "put",
        position: 2,
        strike: -5,
        dte: 30,
      },
      {
        type: "put",
        position: -1,
        strike: 0,
        dte: 30,
      },
    ],
  },
  longCallCondor: {
    id: 30,
    slug: "long-call-condor",
    name: "Long Call Condor",
    aliases: [],
    level: "Advanced",
    sentiment: ["neutral"],
    category: "Neutral",
    description: "Similar to a long call butterfly, but the middle options have different strikes. It has a wider profitable range than a long call butterfly, but the potential profit is lower and the maximum loss is higher.",
    template: [
      {
        type: "call",
        position: 1,
        strike: -10,
        dte: 30,
      },
      {
        type: "call",
        position: -1,
        strike: -5,
        dte: 30,
      },
      {
        type: "call",
        position: -1,
        strike: 5,
        dte: 30,
      },
      {
        type: "call",
        position: 1,
        strike: 10,
        dte: 30,
      },
    ],
  },
  longPutCondor: {
    id: 31,
    slug: "long-put-condor",
    name: "Long Put Condor",
    aliases: [],
    level: "Advanced",
    sentiment: ["neutral"],
    category: "Neutral",
    description: "Similar to a long put butterfly, but the middle options have different strikes. It has a wider profitable range than a long put butterfly, but the potential profit is lower and the maximum loss is higher.",
    template: [
      {
        type: "put",
        position: 1,
        strike: -10,
        dte: 30,
      },
      {
        type: "put",
        position: -1,
        strike: -5,
        dte: 30,
      },
      {
        type: "put",
        position: -1,
        strike: 5,
        dte: 30,
      },
      {
        type: "put",
        position: 1,
        strike: 10,
        dte: 30,
      },
    ],
  },
  shortCallCondor: {
    id: 32,
    slug: "short-call-condor",
    name: "Short Call Condor",
    aliases: [],
    level: "Advanced",
    sentiment: ["directional"],
    category: "Directional",
    description: "Similar to a short call butterfly, but the middle options have different strikes. It has a wider unprofitable range than a short call butterfly, but the potential profit outside of that range is higher and the maximum loss is lower",
    template: [
      {
        type: "call",
        position: -1,
        strike: -10,
        dte: 30,
      },
      {
        type: "call",
        position: 1,
        strike: -5,
        dte: 30,
      },
      {
        type: "call",
        position: 1,
        strike: 5,
        dte: 30,
      },
      {
        type: "call",
        position: -1,
        strike: 10,
        dte: 30,
      },
    ],
  },
  shortPutCondor: {
    id: 33,
    slug: "short-put-condor",
    name: "Short Put Condor",
    aliases: [],
    level: "Advanced",
    sentiment: ["directional"],
    category: "Directional",
    description: "Similar to a short put butterfly, but the middle options have different strikes. It has a wider unprofitable range than a short put butterfly, but the potential profit outside of that range is higher and the maximum loss is lower.",
    template: [
      {
        type: "put",
        position: -1,
        strike: -10,
        dte: 30,
      },
      {
        type: "put",
        position: 1,
        strike: -5,
        dte: 30,
      },
      {
        type: "put",
        position: 1,
        strike: 5,
        dte: 30,
      },
      {
        type: "put",
        position: -1,
        strike: 10,
        dte: 30,
      },
    ],
  },
  inverseIronButterfly: {
    id: 34,
    slug: "inverse-iron-butterfly",
    name: "Inverse Iron Butterfly",
    aliases: ["Long Iron Butterfly"],
    level: "Intermediate",
    sentiment: ["directional"],
    category: "Directional",
    description:
      "The opposite of a iron butterfly. This strategy is a net debit and unlike the long butterfly, it doesn't offer a very risk/reward ratio. If the stock moves in either direction you can net a small profit. If volatility increases, the profitable range and chance of profit will increase as well. Time is harmful when the position is unprofitable, but helpful once it becomes profitable.",
    template: [
      {
        type: "put",
        position: -1,
        strike: -5,
        dte: 30,
      },
      {
        type: "put",
        position: 1,
        strike: 0,
        dte: 30,
      },
      {
        type: "call",
        position: 1,
        strike: 0,
        dte: 30,
      },
      {
        type: "call",
        position: -1,
        strike: 5,
        dte: 30,
      },
    ],
  },
  inverseIronCondor: {
    id: 35,
    slug: "inverse-iron-condor",
    name: "Inverse Iron Condor",
    aliases: ["Long Iron Condor"],
    level: "Intermediate",
    sentiment: ["directional"],
    category: "Directional",
    description: "The opposite of a iron condor, and similar to a short iron butterfly, but with a wider unprofitable range and better potential profit. If volatility increases, the profitable range and chance of profit will increase as well. Time is harmful when the position is unprofitable, but helpful once it becomes profitable.",
    template: [
      {
        type: "put",
        position: -1,
        strike: -10,
        dte: 30,
      },
      {
        type: "put",
        position: 1,
        strike: -5,
        dte: 30,
      },
      {
        type: "call",
        position: 1,
        strike: 5,
        dte: 30,
      },
      {
        type: "call",
        position: -1,
        strike: 10,
        dte: 30,
      },
    ],
  },
  coveredShortStraddle: {
    id: 36,
    slug: "covered-short-straddle",
    name: "Covered Short Straddle",
    aliases: [],
    level: "Advanced",
    sentiment: ["bullish", "income"],
    category: "Income",
    description:
      "A risky income strategy which increases the yield of a covered call by selling a put for additional income. The put is not covered and causes the risk to nearly double. If the stock drops significantly, this strategy can lose significant money. Since this strategy involves a short put and call, one will likely be exercised unless the price is at strike A at expiration. Time is helpful to this strategy as the value of the options will decay.",
    template: [
      {
        type: "stock",
        position: 1,
      },
      {
        type: "call",
        position: -1,
        strike: 0,
        dte: 30,
      },
      {
        type: "put",
        position: -1,
        strike: 0,
        dte: 30,
      },
    ],
  },
  coveredShortStrangle: {
    id: 37,
    slug: "covered-short-strangle",
    name: "Covered Short Strangle",
    aliases: [],
    level: "Advanced",
    sentiment: ["bullish", "income"],
    category: "Income",
    description:
      "A risky income strategy which increases the yield of a covered call by selling an out of the money put for additional income. It is similar to a covered straddle but doesn't introduce as much risk. If the stock falls below strike A, the put will be exercised and you must buy 100 shares of the underlying at strike A. If it rises above strike B, the call will be exercised and the underlying position will be sold. Time is helpful to this strategy as the value of the options will decay.",
    template: [
      {
        type: "stock",
        position: 1,
      },
      {
        type: "put",
        position: -1,
        strike: -5,
        dte: 30,
      },
      {
        type: "call",
        position: -1,
        strike: 5,
        dte: 30,
      },
    ],
  },
  shortStraddle: {
    id: 38,
    slug: "short-straddle",
    name: "Short Straddle",
    aliases: [],
    level: "Advanced",
    sentiment: ["neutral"],
    category: "Neutral",
    description: "The opposite of a long straddle. This strategy makes good income since a put and call are being sold, but requires minimal stock movement as the max loss is uncapped in both directions. Time is beneficial for this strategy as both options will decay and become cheaper to buy back, but since there is unlimited risk you also don't want to be exposed for too long.",
    template: [
      {
        type: "put",
        position: -1,
        strike: 0,
        dte: 30,
      },
      {
        type: "call",
        position: -1,
        strike: 0,
        dte: 30,
      },
    ],
  },
  shortStrangle: {
    id: 39,
    slug: "short-strangle",
    name: "Short Strangle",
    aliases: [],
    level: "Advanced",
    sentiment: ["neutral"],
    category: "Neutral",
    description:
      "The opposite of a long strangle, and similar to a short straddle but with different strikes. This strategy makes less income than a short straddle, but also has a wider profitable range, making the worst case scenario less likely. Time is beneficial for this strategy as both options will decay and become cheaper to buy back, but like a short straddle, there is unlimited risk so you don't want to be exposed for too long.",
    template: [
      {
        type: "put",
        position: -1,
        strike: -5,
        dte: 30,
      },
      {
        type: "call",
        position: -1,
        strike: 5,
        dte: 30,
      },
    ],
  },
  brokenWingCalls: {
    id: 40,
    slug: "call-broken-wing",
    name: "Call Broken Wing",
    aliases: ["Skip Strike Butterfly"],
    level: "Advanced",
    sentiment: ["bearish"],
    category: "Ratio Spreads",
    description: "Similar to a call butterfly spread, but with a slightly bearish bias. It has a higher chance of profit and removes risk from one side. Time is generally harmful, except when it is profitable near strike B.",
    template: [
      {
        type: "call",
        position: 1,
        strike: -10,
        dte: 30,
      },
      {
        type: "call",
        position: -2,
        strike: -5,
        dte: 30,
      },
      {
        type: "call",
        position: 1,
        strike: 10,
        dte: 30,
      },
    ],
  },
  brokenWingPuts: {
    id: 41,
    slug: "put-broken-wing",
    name: "Put Broken Wing",
    aliases: ["Skip Strike Butterfly"],
    level: "Advanced",
    sentiment: ["bullish"],
    category: "Ratio Spreads",
    description: "Similar to a put butterfly spread, but with a slightly bullish bias. It has a higher chance of profit and removes risk from one side. Time is generally harmful, except when it is profitable near strike B.",
    template: [
      {
        type: "put",
        position: 1,
        strike: -10,
        dte: 30,
      },
      {
        type: "put",
        position: -2,
        strike: 5,
        dte: 30,
      },
      {
        type: "put",
        position: 1,
        strike: 10,
        dte: 30,
      },
    ],
  },
  inverseBrokenWingCalls: {
    id: 42,
    slug: "inverse-call-broken-wing",
    name: "Inverse Call Broken Wing",
    aliases: ["Inverse Skip Strike Butterfly"],
    level: "Advanced",
    sentiment: ["bullish"],
    category: "Ratio Spreads",
    description: "Opposite of a call broken wing, and similar to a short call butterfly. It has a bullish bias and a lower chance of profit compared to a butterfly, but a higher max profit.",
    template: [
      {
        type: "call",
        position: -1,
        strike: -10,
        dte: 30,
      },
      {
        type: "call",
        position: 2,
        strike: -5,
        dte: 30,
      },
      {
        type: "call",
        position: -1,
        strike: 10,
        dte: 30,
      },
    ],
  },
  inverseBrokenWingPuts: {
    id: 43,
    slug: "inverse-put-broken-wing",
    name: "Inverse Put Broken Wing",
    aliases: ["Inverse Skip Strike Butterfly"],
    level: "Advanced",
    sentiment: ["bearish"],
    category: "Ratio Spreads",
    description: "Opposite of a put broken wing, and similar to a short put butterfly. It has a bearish bias and a lower chance of profit compared to a butterfly, but a higher max profit.",
    template: [
      {
        type: "put",
        position: -1,
        strike: -10,
        dte: 30,
      },
      {
        type: "put",
        position: 2,
        strike: 5,
        dte: 30,
      },
      {
        type: "put",
        position: -1,
        strike: 10,
        dte: 30,
      },
    ],
  },
  doubleDiagonal: {
    id: 44,
    slug: "double-diagonal",
    name: "Double Diagonal",
    aliases: [],
    level: "Expert",
    sentiment: ["neutral"],
    category: "Other",
    description: "An expert strategy that is the combination of a diagonal call spread and a diagonal put spread. As time passes, the profitability range will increase.",
    template: [
      {
        type: "put",
        position: 1,
        strike: -10,
        dte: 60,
      },
      {
        type: "put",
        position: -1,
        strike: -5,
        dte: 30,
      },
      {
        type: "call",
        position: -1,
        strike: 5,
        dte: 30,
      },
      {
        type: "call",
        position: 1,
        strike: 10,
        dte: 60,
      },
    ],
  },
  strap: {
    id: 45,
    slug: "strap",
    name: "Strap",
    aliases: [],
    level: "Expert",
    sentiment: ["directional", "bullish"],
    category: "Other",
    description:
      "Similar to a straddle, but with a more bullish bias by buying double the amount of calls. The stock must move to make a profit, but it will now make more if it moves up than if it moves down. Time works against this strategy as it will decay. Increasing volatility will be helpful in pushing the stock in a direction, as well as increasing the value of your position as implied volatility rises.",
    template: [
      {
        type: "call",
        position: 2,
        strike: 0,
        dte: 30,
      },
      {
        type: "put",
        position: 1,
        strike: 0,
        dte: 30,
      },
    ],
  },
  strip: {
    id: 46,
    slug: "strip",
    name: "Strip",
    aliases: [],
    level: "Expert",
    sentiment: ["directional", "bearish"],
    category: "Other",
    description:
      "Similar to a straddle, but with a more bearish bias by buying double the amount of puts. The stock must move to make a profit, but it will now make more if it moves down than if it moves up. Time works against this strategy as it will decay. Increasing volatility will be helpful in pushing the stock in a direction, as well as increasing the value of your position as implied volatility rises.",
    template: [
      {
        type: "call",
        position: 1,
        strike: 0,
        dte: 30,
      },
      {
        type: "put",
        position: 2,
        strike: 0,
        dte: 30,
      },
    ],
  },
  ratioCallSpread: {
    id: 47,
    slug: "call-ratio-spread",
    name: "Call Ratio Spread",
    aliases: [],
    level: "Expert",
    sentiment: ["bullish"],
    category: "Ratio Spreads",
    description: "The opposite of a call ratio backspread. It is a neutral to slightly bullish strategy with unlimited risk if the stock moves up too much. Time is helpful to this strategy (although you don't want to be exposed for too long), but increasing volatility is harmful.",
    template: [
      {
        type: "call",
        position: 1,
        strike: 0,
        dte: 30,
      },
      {
        type: "call",
        position: -2,
        strike: 5,
        dte: 30,
      },
    ],
  },
  ratioPutSpread: {
    id: 48,
    slug: "put-ratio-spread",
    name: "Put Ratio Spread",
    aliases: [],
    level: "Expert",
    sentiment: ["bearish"],
    category: "Ratio Spreads",
    description: "The opposite of a put ratio backspread. It is a neutral to slightly bearish strategy with unlimited risk if the stock moves down too much. Time is helpful to this strategy (although you don't want to be exposed for too long), but increasing volatility is harmful.",
    template: [
      {
        type: "put",
        position: -2,
        strike: -5,
        dte: 30,
      },
      {
        type: "put",
        position: 1,
        strike: 0,
        dte: 30,
      },
    ],
  },
  guts: {
    id: 49,
    slug: "guts",
    name: "Guts",
    aliases: [],
    level: "Expert",
    sentiment: ["directional"],
    category: "Other",
    description: "Similar to a strangle (max profit, max risk, and chance of profit is the same), but more expensive because the put and call positions are reversed. Outside of very specific circumstances, there is no reason to trade a guts over a strangle. (A strangle will also have more liquid options, as they are out-of-the money while guts uses in-the-money options)",
    template: [
      {
        type: "call",
        position: 1,
        strike: -5,
        dte: 30,
      },
      {
        type: "put",
        position: 1,
        strike: 5,
        dte: 30,
      },
    ],
  },
  shortGuts: {
    id: 50,
    slug: "short-guts",
    name: "Short Guts",
    aliases: [],
    level: "Expert",
    sentiment: ["neutral"],
    category: "Other",
    description: "The opposite of guts, and similar to a short straddle.",
    template: [
      {
        type: "call",
        position: -1,
        strike: -5,
        dte: 30,
      },
      {
        type: "put",
        position: -1,
        strike: 5,
        dte: 30,
      },
    ],
  },
  longSyntheticFuture: {
    id: 51,
    slug: "long-synthetic-future",
    name: "Long Synthetic Future",
    aliases: [],
    level: "Expert",
    sentiment: ["bullish"],
    category: "Synthetic",
    description: 'This strategy recreates the risk profile of a long stock position by buying an at-the-money call and selling an at-the-money put. It is usually established as a very small credit or debit, making it a "no cost" alternative to owning a stock and allowing you to have leverage without an up-front cost. Remember that because this strategy has a short put, it has assignment risk.',
    template: [
      {
        type: "put",
        position: -1,
        strike: 0,
        dte: 30,
      },
      {
        type: "call",
        position: 1,
        strike: 0,
        dte: 30,
      },
    ],
  },
  shortSyntheticFuture: {
    id: 52,
    slug: "short-synthetic-future",
    name: "Short Synthetic Future",
    aliases: [],
    level: "Expert",
    sentiment: ["bearish"],
    category: "Synthetic",
    description: "This strategy recreates the risk profile of a short stock position by selling an at-the-money call and buying an at-the-money put. It is usually established as a very small credit or debit. Remember that because this strategy has a short call, it has assignment risk.",
    template: [
      {
        type: "put",
        position: 1,
        strike: 0,
        dte: 30,
      },
      {
        type: "call",
        position: -1,
        strike: 0,
        dte: 30,
      },
    ],
  },
  syntheticPut: {
    id: 53,
    slug: "synthetic-put",
    name: "Synthetic Put",
    aliases: ["Protective Call"],
    level: "Expert",
    sentiment: ["bearish"],
    category: "Synthetic",
    description: "A bearish strategy used to replicate the profit potential of a put using a call and shorting the underlying stock. The call will protect the short position from losing too much if the stock moves upwards.",
    template: [
      {
        type: "stock",
        position: -1,
      },
      {
        type: "call",
        position: 1,
        strike: 0,
        dte: 30,
      },
    ],
  },
  longCombo: {
    id: 54,
    slug: "long-combo",
    name: "Long Combo",
    aliases: [],
    level: "Expert",
    sentiment: ["bullish"],
    category: "Arbitrage",
    description: "Similar to a long synthetic future, but with a distance between strikes. This makes the trade have no return or loss between the strikes at expiration, and only gain or lose if the stock goes below strike A or above strike B. Further from expiration, it behaves like a synthetic future.",
    template: [
      {
        type: "put",
        position: -1,
        strike: -5,
        dte: 30,
      },
      {
        type: "call",
        position: 1,
        strike: 5,
        dte: 30,
      },
    ],
  },
  shortCombo: {
    id: 55,
    slug: "short-combo",
    name: "Short Combo",
    aliases: [],
    level: "Expert",
    sentiment: ["bearish"],
    category: "Arbitrage",
    description: "Similar to a short synthetic future, but with a distance between strikes. This makes the trade have no return or loss between the strikes at expiration, and only gain or lose if the stock goes below strike A or above strike B. Further from expiration, it behaves like a short synthetic future.",
    template: [
      {
        type: "put",
        position: 1,
        strike: -5,
        dte: 30,
      },
      {
        type: "call",
        position: -1,
        strike: 5,
        dte: 30,
      },
    ],
  },
  cashSecuredPut: {
    id: 56,
    slug: "cash-secured-put",
    name: "Cash-Secured Put",
    aliases: [],
    level: "Advanced",
    sentiment: ["income"],
    category: "Other",
    description:
      "A simple income strategy for neutral to slightly-bearish  situations when you are willing to acquire stock at strike price A (making you bullish in the long term). By selling a cash-secured put, you receive a small premium and the obligation to buy 100 shares of the underlying if the stock expires below strike A and you are assigned. This allows you to make consistent income while also having the chance of purchasing the stock at a lower price if reached. The downside is that the stock could continue falling, causing you to buy a price that is much higher than the current price.",
    template: [
      {
        type: "put",
        position: -1,
        strike: 0,
        dte: 30,
      },
    ],
  },
  jadeLizard: {
    id: 56,
    slug: "jade-lizard",
    name: "Jade Lizard",
    aliases: [],
    level: "Advanced",
    sentiment: ["bullish"],
    category: "Other",
    description: "A slightly bullish strategy combining an out-of-the-money short put and out-of-the-money bear call spread. When created properly, this strategy has no upside risk. It is best suited for oversold stocks with high implied volatility.",
    template: [
      {
        type: "put",
        position: -1,
        strike: -2.5,
        dte: 30,
      },
      {
        type: "call",
        position: -1,
        strike: -2.5,
        dte: 30,
      },
      {
        type: "call",
        position: 1,
        strike: 4.5,
        dte: 30,
      },
    ],
  },
  reverseJadeLizard: {
    id: 57,
    slug: "reverse-jade-lizard",
    name: "Reverse Jade Lizard",
    aliases: [],
    level: "Advanced",
    sentiment: ["bearish"],
    category: "Other",
    description: "A slightly bearish strategy combining an out-of-the-money short call and out-of-the-money bull put spread. When created properly, this strategy has no downside risk. It is best suited for overbought stocks with high implied volatility.",
    template: [
      {
        type: "put",
        position: 1,
        strike: -4.5,
        dte: 30,
      },
      {
        type: "put",
        position: -1,
        strike: -2.5,
        dte: 30,
      },
      {
        type: "call",
        position: -1,
        strike: 2.5,
        dte: 30,
      },
    ],
  },
  reverseCalendarCallSpread: {
    id: 58,
    slug: "reverse-calendar-call-spread",
    name: "Reverse Calendar Call Spread",
    aliases: ["Reverse Horizontal Call Spread"],
    level: "Intermediate",
    sentiment: ["directional"],
    category: "Other",
    description: "An inverted calendar call spread.",
    template: [
      {
        type: "call",
        position: 1,
        strike: 0,
        dte: 30,
      },
      {
        type: "call",
        position: -1,
        strike: 0,
        dte: 60,
      },
    ],
  },
  reverseCalendarPutSpread: {
    id: 59,
    slug: "reverse-calendar-put-spread",
    name: "Reverse Calendar Put Spread",
    aliases: ["Reverse Horizontal Put Spread"],
    level: "Intermediate",
    sentiment: ["directional"],
    category: "Other",
    description: "An inverted calendar put spread.",
    template: [
      {
        type: "put",
        position: 1,
        strike: 0,
        dte: 30,
      },
      {
        type: "put",
        position: -1,
        strike: 0,
        dte: 60,
      },
    ],
  },
  reverseDiagonalCallSpread: {
    id: 60,
    slug: "reverse-diagonal-call-spread",
    name: "Reverse Diagonal Call Spread",
    aliases: [],
    level: "Intermediate",
    sentiment: ["bearish"],
    category: "Other",
    description: "A reverse diagonal call spread.",
    template: [
      {
        type: "call",
        position: 1,
        strike: 5,
        dte: 30,
      },
      {
        type: "call",
        position: -1,
        strike: -5,
        dte: 60,
      },
    ],
  },
  reverseDiagonalPutSpread: {
    id: 61,
    slug: "reverse-diagonal-put-spread",
    name: "Reverse Diagonal Put Spread",
    aliases: [],
    level: "Intermediate",
    sentiment: ["bullish"],
    category: "Other",
    description: "A reverse diagonal put spread.",
    template: [
      {
        type: "put",
        position: 1,
        strike: -5,
        dte: 30,
      },
      {
        type: "put",
        position: -1,
        strike: 5,
        dte: 60,
      },
    ],
  },
  longCalls: {
    id: 101,
    slug: "long-calls",
    name: "Long Calls",
    aliases: [],
    level: "Novice",
    sentiment: [],
    category: "Basic",
    description: "",
    template: [
      {
        type: "call",
        position: 1,
        strike: -5,
        dte: 30,
      },
      {
        type: "call",
        position: 1,
        strike: 5,
        dte: 30,
      },
    ],
  },
  longPuts: {
    id: 102,
    slug: "long-puts",
    name: "Long Puts",
    aliases: [],
    level: "Novice",
    sentiment: [],
    category: "Basic",
    description: "",
    template: [
      {
        type: "put",
        position: 1,
        strike: -5,
        dte: 30,
      },
      {
        type: "put",
        position: 1,
        strike: 5,
        dte: 30,
      },
    ],
  },
  shortCalls: {
    id: 103,
    slug: "short-calls",
    name: "Short Calls",
    aliases: [],
    level: "Advanced",
    sentiment: [],
    category: "Naked",
    description: "",
    template: [
      {
        type: "call",
        position: -1,
        strike: -5,
        dte: 30,
      },
      {
        type: "call",
        position: -1,
        strike: 5,
        dte: 30,
      },
    ],
  },
  shortPuts: {
    id: 104,
    slug: "short-puts",
    name: "Short Puts",
    aliases: [],
    level: "Advanced",
    sentiment: [],
    category: "Naked",
    description: "",
    template: [
      {
        type: "put",
        position: -1,
        strike: -5,
        dte: 30,
      },
      {
        type: "put",
        position: -1,
        strike: 5,
        dte: 30,
      },
    ],
  },
  longEquity: {
    id: 105,
    slug: "long-stock",
    name: "Long Stock",
    aliases: [],
    level: "Novice",
    sentiment: ["bullish"],
    category: "Basic",
    description: "Long stock simply means that you own the stock. To profit, the stock needs to go up from where you bought it at. Your profit or loss is not locked in until you sell the stock.",
    template: [
      {
        type: "stock",
        position: 1,
      },
    ],
  },
  shortEquity: {
    id: 106,
    slug: "short-stock",
    name: "Short Stock",
    aliases: [],
    level: "Novice",
    sentiment: ["bearish"],
    category: "Basic",
    description: "Short stock means that you are short selling the stock. The profit and loss is reversed compared to owning the stock. Short selling can be used to hedge bullish positions or to speculate on a potential decline in price. To profit, you need to buy the stock back at a lower price than you sold it for.",
    template: [
      {
        type: "stock",
        position: -1,
      },
    ],
  },
  doubleCalendar: {
    id: 108,
    slug: "double-calendar",
    name: "Double Calendar",
    aliases: [],
    level: "Expert",
    sentiment: ["neutral"],
    category: "Other",
    description: "A expert strategy that is the combination of a calendar call spread and a calendar put spread. As time passes, the profitability range will increase.",
    template: [
      {
        type: "put",
        position: 1,
        strike: -5,
        dte: 60,
      },
      {
        type: "put",
        position: -1,
        strike: -5,
        dte: 30,
      },
      {
        type: "call",
        position: -1,
        strike: 5,
        dte: 30,
      },
      {
        type: "call",
        position: 1,
        strike: 5,
        dte: 60,
      },
    ],
  },
  custom: {
    id: 0,
    slug: "custom",
    name: "Custom",
    aliases: [],
    level: "Expert",
    sentiment: [],
    category: "Other",
    description: "",
    template: [
      {
        type: "call",
        position: 1,
        strike: 0,
        dte: 30,
      },
    ],
  },
} satisfies Record<string, Strategy>;
